# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: TRADUC'TIK
  fr: TRADUC'TIK
  
languages:
  en: English
  fr: French
  
languages-localized:
  en: English
  fr: Français

email: traductik@traductik.fr

logo:
  en: img/logos/logo-traductik_EN.svg
  fr: img/logos/logo-traductik_FR.svg
  
description:
  en: Your partner for translating, interpreting, editing, subtitling, voice-over...
  fr: Votre partenaire en traduction, interprétation, rédaction, sous-titrages, voix off...
  
index:
  en: accueil_en
  fr: accueil_fr
  
index-name:
  en: Home
  fr: Accueil
  
feed:
  en: /en_feed.xml
  fr: /fr_feed.xml  

baseurl: "" # the subpath of your site, e.g. /blog
url: "01traduction.fr/" # the base hostname & protocol for your site

twitter_username: traductik
github_username:  traductik

permalink: /:categories/:title/

#Collections
collections:
  services:
    output: true
    en: services
    fr: services
    permalink: /services/:path/
  


# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
